In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('jiomart.csv')

In [3]:
df.head()

,Unnamed: 0,fruits,vegetables,Dairy,toast & Khari,Atta & Flours,Dal & Pulces,Rice & rice products,Masalas,Salt-Sugar-Jaggery,Dry Fruits
0,0,₹ 149.00,₹ 215.00,₹ 52.20,₹ 68.00,₹ 66.00,₹ 479.00,₹ 33.75,₹ 59.00,₹ 12.00,₹ 40.00
1,1,₹ 239.00,₹ 195.00,₹ 62.00,₹ 339.00,₹ 144.00,₹ 39.00,₹ 34.50,₹ 60.00,₹ 42.00,₹ 169.00
2,2,₹ 109.00,₹ 35.00,₹ 33.48,₹ 495.00,₹ 46.00,₹ 345.00,₹ 37.50,₹ 116.00,₹ 22.00,₹ 159.00
3,3,₹ 215.00,₹ 99.00,₹ 18.60,₹ 545.00,₹ 135.00,₹ 25.00,₹ 22.50,₹ 47.00,₹ 32.00,₹ 149.00
4,4,₹ 629.00,₹ 18.00,₹ 44.00,₹ 99.00,₹ 129.00,₹ 169.00,₹ 30.00,₹ 11.50,₹ 26.00,₹ 64.00

In [6]:
df1 = df.drop('Unnamed: 0', axis=1)

In [7]:
df1.head()

,fruits,vegetables,Dairy,toast & Khari,Atta & Flours,Dal & Pulces,Rice & rice products,Masalas,Salt-Sugar-Jaggery,Dry Fruits
0,₹ 149.00,₹ 215.00,₹ 52.20,₹ 68.00,₹ 66.00,₹ 479.00,₹ 33.75,₹ 59.00,₹ 12.00,₹ 40.00
1,₹ 239.00,₹ 195.00,₹ 62.00,₹ 339.00,₹ 144.00,₹ 39.00,₹ 34.50,₹ 60.00,₹ 42.00,₹ 169.00
2,₹ 109.00,₹ 35.00,₹ 33.48,₹ 495.00,₹ 46.00,₹ 345.00,₹ 37.50,₹ 116.00,₹ 22.00,₹ 159.00
3,₹ 215.00,₹ 99.00,₹ 18.60,₹ 545.00,₹ 135.00,₹ 25.00,₹ 22.50,₹ 47.00,₹ 32.00,₹ 149.00
4,₹ 629.00,₹ 18.00,₹ 44.00,₹ 99.00,₹ 129.00,₹ 169.00,₹ 30.00,₹ 11.50,₹ 26.00,₹ 64.00

In [8]:
df1.describe()

,fruits,vegetables,Dairy,toast & Khari,Atta & Flours,Dal & Pulces,Rice & rice products,Masalas,Salt-Sugar-Jaggery,Dry Fruits
count,15,18,20,19,14,19,10,16,18,13
unique,15,18,20,19,14,19,10,16,18,13
top,₹ 100.44,₹ 134.85,₹ 58.50,₹ 29.00,₹ 119.00,₹ 32.55,₹ 30.00,₹ 28.00,₹ 40.00,₹ 159.00
freq,1,1,1,1,1,1,1,1,1,1

In [9]:
df1.shape

(20, 10)

In [10]:
df1.isnull().sum()

fruits                   5
vegetables               2
Dairy                    0
toast & Khari            1
Atta & Flours            6
Dal & Pulces             1
Rice & rice products    10
Masalas                  4
Salt-Sugar-Jaggery       2
Dry Fruits               7
dtype: int64

In [11]:
df1.fillna(method="ffill", limit=2)

,fruits,vegetables,Dairy,toast & Khari,Atta & Flours,Dal & Pulces,Rice & rice products,Masalas,Salt-Sugar-Jaggery,Dry Fruits
0,₹ 149.00,₹ 215.00,₹ 52.20,₹ 68.00,₹ 66.00,₹ 479.00,₹ 33.75,₹ 59.00,₹ 12.00,₹ 40.00
1,₹ 239.00,₹ 195.00,₹ 62.00,₹ 339.00,₹ 144.00,₹ 39.00,₹ 34.50,₹ 60.00,₹ 42.00,₹ 169.00
2,₹ 109.00,₹ 35.00,₹ 33.48,₹ 495.00,₹ 46.00,₹ 345.00,₹ 37.50,₹ 116.00,₹ 22.00,₹ 159.00
3,₹ 215.00,₹ 99.00,₹ 18.60,₹ 545.00,₹ 135.00,₹ 25.00,₹ 22.50,₹ 47.00,₹ 32.00,₹ 149.00
4,₹ 629.00,₹ 18.00,₹ 44.00,₹ 99.00,₹ 129.00,₹ 169.00,₹ 30.00,₹ 11.50,₹ 26.00,₹ 64.00
5,₹ 145.00,₹ 60.00,₹ 161.10,₹ 499.00,₹ 69.00,₹ 22.00,₹ 40.00,₹ 97.00,₹ 34.50,₹ 119.00
6,₹ 319.00,₹ 41.00,₹ 41.85,₹ 229.00,₹ 51.00,₹ 28.00,₹ 99.04,₹ 61.00,₹ 44.50,₹ 39.00
7,₹ 283.65,₹ 80.50,₹ 59.40,₹ 179.00,₹ 90.00,₹ 74.00,₹ 38.86,₹ 185.00,₹ 21.00,₹ 99.00
8,₹ 134.85,₹ 79.00,₹ 56.70,₹ 879.00,₹ 59.52,₹ 37.00,₹ 65.66,₹ 18.00,₹ 40.00,₹ 49.00
9,₹ 269.00,₹ 97.00,₹ 67.50,₹ 289.00,₹ 75.00,₹ 38.00,₹ 19.00,₹ 65.00,₹ 27.00,₹ 85.00
10,₹ 299.00,₹ 134.85,₹ 31.00,₹ 235.00,₹ 80.00,₹ 325.50,₹ 19.00,₹ 26.25,₹ 20.00,₹ 109.00
11,₹ 249.00,₹ 153.00,₹ 82.77,₹ 195.00,₹ 46.50,₹ 32.55,₹ 19.00,₹ 361.00,₹ 39.00,₹ 55.00
12,₹ 99.00,₹ 47.00,₹ 58.50,₹ 589.00,₹ 172.05,₹ 72.54,NaN,₹ 49.00,₹ 135.00,₹ 89.00
13,₹ 100.44,₹ 19.00,₹ 138.00,₹ 29.00,₹ 119.00,₹ 20.00,NaN,₹ 29.75,₹ 18.00,₹ 89.00
14,₹ 106.95,₹ 32.00,₹ 55.80,₹ 389.00,₹ 119.00,₹ 23.25,NaN,₹ 455.00,₹ 29.00,₹ 89.00
15,₹ 106.95,₹ 34.00,₹ 29.00,₹ 46.33,₹ 119.00,₹ 80.10,NaN,₹ 28.00,₹ 34.00,NaN
16,₹ 106.95,₹ 89.00,₹ 68.00,₹ 39.00,NaN,₹ 42.30,NaN,₹ 28.00,₹ 39.50,NaN
17,NaN,₹ 55.00,₹ 64.80,₹ 27.00,NaN,₹ 38.70,NaN,₹ 28.00,₹ 8.00,NaN
18,NaN,₹ 55.00,₹ 63.00,₹ 49.00,NaN,₹ 71.10,NaN,NaN,₹ 8.00,NaN
19,NaN,₹ 55.00,₹ 48.60,₹ 49.00,NaN,₹ 71.10,NaN,NaN,₹ 8.00,NaN

In [30]:
df3 = df1.fillna(method="ffill", axis=1, limit=4)

In [31]:
df3

,fruits,vegetables,Dairy,toast & Khari,Atta & Flours,Dal & Pulces,Rice & rice products,Masalas,Salt-Sugar-Jaggery,Dry Fruits
0,₹ 149.00,₹ 215.00,₹ 52.20,₹ 68.00,₹ 66.00,₹ 479.00,₹ 33.75,₹ 59.00,₹ 12.00,₹ 40.00
1,₹ 239.00,₹ 195.00,₹ 62.00,₹ 339.00,₹ 144.00,₹ 39.00,₹ 34.50,₹ 60.00,₹ 42.00,₹ 169.00
2,₹ 109.00,₹ 35.00,₹ 33.48,₹ 495.00,₹ 46.00,₹ 345.00,₹ 37.50,₹ 116.00,₹ 22.00,₹ 159.00
3,₹ 215.00,₹ 99.00,₹ 18.60,₹ 545.00,₹ 135.00,₹ 25.00,₹ 22.50,₹ 47.00,₹ 32.00,₹ 149.00
4,₹ 629.00,₹ 18.00,₹ 44.00,₹ 99.00,₹ 129.00,₹ 169.00,₹ 30.00,₹ 11.50,₹ 26.00,₹ 64.00
5,₹ 145.00,₹ 60.00,₹ 161.10,₹ 499.00,₹ 69.00,₹ 22.00,₹ 40.00,₹ 97.00,₹ 34.50,₹ 119.00
6,₹ 319.00,₹ 41.00,₹ 41.85,₹ 229.00,₹ 51.00,₹ 28.00,₹ 99.04,₹ 61.00,₹ 44.50,₹ 39.00
7,₹ 283.65,₹ 80.50,₹ 59.40,₹ 179.00,₹ 90.00,₹ 74.00,₹ 38.86,₹ 185.00,₹ 21.00,₹ 99.00
8,₹ 134.85,₹ 79.00,₹ 56.70,₹ 879.00,₹ 59.52,₹ 37.00,₹ 65.66,₹ 18.00,₹ 40.00,₹ 49.00
9,₹ 269.00,₹ 97.00,₹ 67.50,₹ 289.00,₹ 75.00,₹ 38.00,₹ 19.00,₹ 65.00,₹ 27.00,₹ 85.00
10,₹ 299.00,₹ 134.85,₹ 31.00,₹ 235.00,₹ 80.00,₹ 325.50,₹ 325.50,₹ 26.25,₹ 20.00,₹ 109.00
11,₹ 249.00,₹ 153.00,₹ 82.77,₹ 195.00,₹ 46.50,₹ 32.55,₹ 32.55,₹ 361.00,₹ 39.00,₹ 55.00
12,₹ 99.00,₹ 47.00,₹ 58.50,₹ 589.00,₹ 172.05,₹ 72.54,₹ 72.54,₹ 49.00,₹ 135.00,₹ 89.00
13,₹ 100.44,₹ 19.00,₹ 138.00,₹ 29.00,₹ 119.00,₹ 20.00,₹ 20.00,₹ 29.75,₹ 18.00,₹ 18.00
14,₹ 106.95,₹ 32.00,₹ 55.80,₹ 389.00,₹ 389.00,₹ 23.25,₹ 23.25,₹ 455.00,₹ 29.00,₹ 29.00
15,NaN,₹ 34.00,₹ 29.00,₹ 46.33,₹ 46.33,₹ 80.10,₹ 80.10,₹ 28.00,₹ 34.00,₹ 34.00
16,NaN,₹ 89.00,₹ 68.00,₹ 39.00,₹ 39.00,₹ 42.30,₹ 42.30,₹ 42.30,₹ 39.50,₹ 39.50
17,NaN,₹ 55.00,₹ 64.80,₹ 27.00,₹ 27.00,₹ 38.70,₹ 38.70,₹ 38.70,₹ 8.00,₹ 8.00
18,NaN,NaN,₹ 63.00,₹ 49.00,₹ 49.00,₹ 71.10,₹ 71.10,₹ 71.10,₹ 71.10,₹ 71.10
19,NaN,NaN,₹ 48.60,₹ 48.60,₹ 48.60,₹ 48.60,₹ 48.60,₹ 48.60,₹ 48.60,₹ 48.60

In [32]:
df4 = df3.fillna(method="ffill")

In [33]:
df4

,fruits,vegetables,Dairy,toast & Khari,Atta & Flours,Dal & Pulces,Rice & rice products,Masalas,Salt-Sugar-Jaggery,Dry Fruits
0,₹ 149.00,₹ 215.00,₹ 52.20,₹ 68.00,₹ 66.00,₹ 479.00,₹ 33.75,₹ 59.00,₹ 12.00,₹ 40.00
1,₹ 239.00,₹ 195.00,₹ 62.00,₹ 339.00,₹ 144.00,₹ 39.00,₹ 34.50,₹ 60.00,₹ 42.00,₹ 169.00
2,₹ 109.00,₹ 35.00,₹ 33.48,₹ 495.00,₹ 46.00,₹ 345.00,₹ 37.50,₹ 116.00,₹ 22.00,₹ 159.00
3,₹ 215.00,₹ 99.00,₹ 18.60,₹ 545.00,₹ 135.00,₹ 25.00,₹ 22.50,₹ 47.00,₹ 32.00,₹ 149.00
4,₹ 629.00,₹ 18.00,₹ 44.00,₹ 99.00,₹ 129.00,₹ 169.00,₹ 30.00,₹ 11.50,₹ 26.00,₹ 64.00
5,₹ 145.00,₹ 60.00,₹ 161.10,₹ 499.00,₹ 69.00,₹ 22.00,₹ 40.00,₹ 97.00,₹ 34.50,₹ 119.00
6,₹ 319.00,₹ 41.00,₹ 41.85,₹ 229.00,₹ 51.00,₹ 28.00,₹ 99.04,₹ 61.00,₹ 44.50,₹ 39.00
7,₹ 283.65,₹ 80.50,₹ 59.40,₹ 179.00,₹ 90.00,₹ 74.00,₹ 38.86,₹ 185.00,₹ 21.00,₹ 99.00
8,₹ 134.85,₹ 79.00,₹ 56.70,₹ 879.00,₹ 59.52,₹ 37.00,₹ 65.66,₹ 18.00,₹ 40.00,₹ 49.00
9,₹ 269.00,₹ 97.00,₹ 67.50,₹ 289.00,₹ 75.00,₹ 38.00,₹ 19.00,₹ 65.00,₹ 27.00,₹ 85.00
10,₹ 299.00,₹ 134.85,₹ 31.00,₹ 235.00,₹ 80.00,₹ 325.50,₹ 325.50,₹ 26.25,₹ 20.00,₹ 109.00
11,₹ 249.00,₹ 153.00,₹ 82.77,₹ 195.00,₹ 46.50,₹ 32.55,₹ 32.55,₹ 361.00,₹ 39.00,₹ 55.00
12,₹ 99.00,₹ 47.00,₹ 58.50,₹ 589.00,₹ 172.05,₹ 72.54,₹ 72.54,₹ 49.00,₹ 135.00,₹ 89.00
13,₹ 100.44,₹ 19.00,₹ 138.00,₹ 29.00,₹ 119.00,₹ 20.00,₹ 20.00,₹ 29.75,₹ 18.00,₹ 18.00
14,₹ 106.95,₹ 32.00,₹ 55.80,₹ 389.00,₹ 389.00,₹ 23.25,₹ 23.25,₹ 455.00,₹ 29.00,₹ 29.00
15,₹ 106.95,₹ 34.00,₹ 29.00,₹ 46.33,₹ 46.33,₹ 80.10,₹ 80.10,₹ 28.00,₹ 34.00,₹ 34.00
16,₹ 106.95,₹ 89.00,₹ 68.00,₹ 39.00,₹ 39.00,₹ 42.30,₹ 42.30,₹ 42.30,₹ 39.50,₹ 39.50
17,₹ 106.95,₹ 55.00,₹ 64.80,₹ 27.00,₹ 27.00,₹ 38.70,₹ 38.70,₹ 38.70,₹ 8.00,₹ 8.00
18,₹ 106.95,₹ 55.00,₹ 63.00,₹ 49.00,₹ 49.00,₹ 71.10,₹ 71.10,₹ 71.10,₹ 71.10,₹ 71.10
19,₹ 106.95,₹ 55.00,₹ 48.60,₹ 48.60,₹ 48.60,₹ 48.60,₹ 48.60,₹ 48.60,₹ 48.60,₹ 48.60

In [34]:
df4.to_csv('clean.csv')